### ISSUE TITLE
application closes?

### ISSUE THREAD

**Issue by Aaranaw** [noahc3/PokemonGoTeamManager#4]
When launching the application I can enter my credentials and hit login, a window pops up and closes, at this point all the buttons are greyed out, any advice would be appreciated.

**Comment by noahc3** [comment]
Please edit auth.bat and on a new line put the word 'pause' (no quotes) and send either a screenshot of the window or a copy of the full message displayed.

**Comment by Aaranaw** [comment]
C:\Users\Localadmin\Downloads\Pokemon.GO.Team.Manager.1.3.1>cd libs

C:\Users\Localadmin\Downloads\Pokemon.GO.Team.Manager.1.3.1\libs>cd py

C:\Users\Localadmin\Downloads\Pokemon.GO.Team.Manager.1.3.1\libs\py>cd pogoapi

C:\Users\Localadmin\Downloads\Pokemon.GO.Team.Manager.1.3.1\libs\py\pogoapi>python pogotesting.py /wait
Traceback (most recent call last):
  File "pogotesting.py", line 9, in <module>
    from api import PokeAuthSession
  File "C:\Users\Localadmin\Downloads\Pokemon.GO.Team.Manager.1.3.1\libs\py\pogoapi\api.py", line 1, in <module>
    import requests
ImportError: No module named requests

C:\Users\Localadmin\Downloads\Pokemon.GO.Team.Manager.1.3.1\libs\py\pogoapi>pause
Press any key to continue . . .

**Comment by Aaranaw** [comment]
Installed requests from the scripts folder in c:/python27
new error is
C:\Users\Localadmin\Downloads\Pokemon.GO.Team.Manager.1.3.1>cd libs

C:\Users\Localadmin\Downloads\Pokemon.GO.Team.Manager.1.3.1\libs>cd py

C:\Users\Localadmin\Downloads\Pokemon.GO.Team.Manager.1.3.1\libs\py>cd pogoapi

C:\Users\Localadmin\Downloads\Pokemon.GO.Team.Manager.1.3.1\libs\py\pogoapi>python pogotesting.py /wait
Traceback (most recent call last):
  File "pogotesting.py", line 9, in <module>
    from api import PokeAuthSession
  File "C:\Users\Localadmin\Downloads\Pokemon.GO.Team.Manager.1.3.1\libs\py\pogoapi\api.py", line 7, in <module>
    from session import PogoSession
  File "C:\Users\Localadmin\Downloads\Pokemon.GO.Team.Manager.1.3.1\libs\py\pogoapi\session.py", line 2, in <module>
    from POGOProtos.Networking.Requests import Request_pb2
  File "C:\Users\Localadmin\Downloads\Pokemon.GO.Team.Manager.1.3.1\libs\py\pogoapi\POGOProtos\Networking\Requests\Request_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf

C:\Users\Localadmin\Downloads\Pokemon.GO.Team.Manager.1.3.1\libs\py\pogoapi>pause

**Comment by SkOODaT** [comment]
yea this isnt working anymore since niantic decided to change a bunch of things, something is not working in your apps connection pool, maby too many requests?

**Comment by Aaranaw** [comment]
Ok, I added pip to the path then reran the Install Required Modules
with the ptc do I need to enter the full email address or just the username?

**Comment by noahc3** [comment]
@Aaranaw  just username.

@SkOODaT I'll have a fix out today or tomorrow.

**Comment by noahc3** [comment]
Was this resolved?
